### ISSUE TITLE
Magnified label/text area is smaller than the square created by dragging

### ISSUE THREAD

**Issue by joanball** [zooniverse/notesFromNature#339] opened 2014-05-30 16:17 UTC
This comment came up on the discussion board: 

http://talk.notesfromnature.org/#/boards/BNN0000002/discussions/DNN00002ay?page=1&comment_id=53873bbe241fe13a8500014a  

 by ibclc2
I've noticed that when dealing with longer lines of text or with stacks of two or three labels, attempts to include all of the text or all of the labels do not result in everything being included in the magnified view. Often the square truncates text on the right, or labels at the top. The only way to work with this situation is to transcribe part of the text, click OK to save it, close the square, create a new square surrounding the missing text, select the field that you want to complete, and type the remaining text in the field. I think the magnified text should show all of the text you included when you defined the square. (I am using a Windows 7 laptop with the Chrome browser.) Can this be fixed?

Posted 22 days ago
  by HelenBennett57
Ditto your frustration. I think the popup is a fixed size. It's not always big enough.

**Comment by chrissnyder** [comment] 2015-02-04 20:55
Dupe of #304

**Closed by chrissnyder** 2015-02-04 20:55 UTC
