### ISSUE TITLE
Login issues

### ISSUE THREAD

**Issue by robgur** [zooniverse/notesFromNature#356] opened 2015-03-17 01:56 UTC
@chrissnyder Our most loyal transcriber, Mr. Kevvy, has a serious problem I would very much like to see resolved.  See the transcript below..

_________________________________________________________________________

Mr. Kevvy
No image loads when starting transcription and Discuss links to empty http://talk.notesfromnature.org/#/subjects/ indicating there's no record. Tried on two browsers and two computers from two IP addresses and no change. I tried all of the others (Calbug, Macrofungi and Ornithology) and they all work.

I thought Herbarium was completely down but then I saw another poster indicating an error and the image count has gone down, so I created a test account and it brought up an image. So it's just me.

[I had planned on power-transcribing all weekend (these things always happen with that sort of timing) as it's at 95% to get it completed, but something tells me that it may already be completed and run out of images.]

Anyone else?

Edit: I found I can log out and transcribe anonymously... I'll just have to log in when I leave object comments.. :p This is weird. Well my counter won't go up but so be it. And after each transcription a double image loads and I need to quit and restart. Something is definitely broken. Edit2: After about 5-10 transcriptions the double issue stopped and it seems to be working fine now, but only anonymously. My account still broken.

Posted 3 days ago
  by robgur ADMIN, SCIENTIST
Oof, Mr. Kevvy, is this still not working for you? I will report the problem but REALLY hoping (beyond hope) that this somehow resolved itself?

Posted a day ago
  by Mr. Kevvy
Unfortunately it's still occurring, and I verified this (again) on two different computers, on two different IP addresses, on two different browsers (Chrome and Firefox) that all the NFN projects except Herbarium (of course, the only one I want to do) work when logged in, and Herbarium works only when not logged in, so it's definitely my account. Oh and I had never gone to NFN before on the second test computer to eliminate local residuals ie cookies causing it. Edit: I just tried it from work as well today (Monday 2015 Mar 16) and there is no change...

I really appreciate a response on a weekend and my apologies that it looked for a few hours that Herbarium was down, until I saw someone post that they had the "double image" issue. Happily that appears resolved after a few anonymous transcriptions. I'll just track how many I do and hope that it can be added to my main account total. :^)

Posted 13 hours ago
  by robgur ADMIN, SCIENTIST
Hmmm well let me post this to the issue tracker and see if we might be able to both resolve this AND add to your total count. No stress re: weekend either. Notes from Nature is something we really want to get "right" despite the glitches and hiccups. And sometimes the only time to do that is weekends.

**Comment by chrissnyder** [comment] 2015-03-17 16:28
Sounds like that user has completely transcribed all images in that group. I think I need to add some messaging to communicate this.

**Comment by chrissnyder** [comment] 2015-04-20 13:01
Duplicate of #360

**Closed by chrissnyder** 2015-04-20 13:01 UTC
