### ISSUE TITLE
Herbarium popup often too short/narrow

### ISSUE THREAD

**Issue by joanball** [zooniverse/notesFromNature#341] opened 2014-06-27 20:52 UTC
Complaints that herbarium popup is often not large enough to view entire label...

http://talk.notesfromnature.org/#/boards/BNN0000002/discussions/DNN00002e9?page=1&comment_id=53ada1fc4e041a1edb000255

**Comment by chrissnyder** [comment] 2015-02-04 20:55
Dupe of #304

**Closed by chrissnyder** 2015-02-04 20:55 UTC
