### ISSUE TITLE
Zoom in Macrofungi

### ISSUE THREAD

**Issue by robgur** [zooniverse/notesFromNature#346] opened 2014-09-17 13:24 UTC
We are still getting people fleeing the Macrofungi project because of the problems with zooming.  Here are some recent comments:  

"As a developer myself, this is an unforgivable bug. The zoomed potion of the label is a fixed square from the upper left corner of the box. No matter what size of box you draw, it is always the same size box at the same zoom level. If the program is not going to zoom on what I drew a box around you should remove the feature and just give me a NORMAL zoom button so I can make the WHOLE THING bigger."

**Comment by chrissnyder** [comment] 2015-02-04 20:54
Dupe of #304

**Closed by chrissnyder** 2015-02-04 20:54 UTC
